services:
  produktserver:
    image: mysql:8.4.2
    container_name: produktserver
    restart: always
    env_file:
      - .env
    ports:
      - "3310:3306"
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}


  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8982:8080"
